# Generated by Django 2.0 on 2018-01-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180103_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='text',
            field=models.TextField(max_length=50),
        ),
    ]
